Refactor/Edit Package
apeun-gidaechi/seugi-android pull request #180
Opened 2024-07-25 08:21 UTC by wnsgur1

## 개요 (필수)

- 패키지를 화면단위로 나눴습니다.

## 이슈 번호

- close #178

2024-07-25 08:26 UTC, 8954sood requested changes
흠.. navigation을 제가 고려를 안했었네요.
screen, navigation은 같은 레벨이 아니기에 아래와 같은 구조로 변경해보시는건 어떨까요?

- navigation
  -- 각각의 네비게이션들
- screen
  -- selectingcode
     -- SelectingCodeScreen
     -- etc..
     
참고로, 패키지 이름에는 절대 대문자가 들어가서는 안돼요!

2024-07-25 08:30 UTC, wnsgur1 commented
> 흠.. navigation을 제가 고려를 안했었네요. screen, navigation은 같은 레벨이 아니기에 아래와 같은 구조로 변경해보시는건 어떨까요?
> 
> * navigation
>   -- 각각의 네비게이션들
> * screen
>   -- selectingcode
>   -- SelectingCodeScreen
>   -- etc..
> 
> 참고로, 패키지 이름에는 절대 대문자가 들어가서는 안돼요!

2024-07-25 08:32 UTC, wnsgur1 commented
그럼 viewMdoel은 어떻게 처리하나요? viewModel 패키지를 만들어야 할까요

2024-07-25 08:33 UTC, wnsgur1 commented
그리고 패키지에 대문자가 안된다면 school_code 이런식으로 해야하나요?

2024-07-25 09:04 UTC, 8954sood commented
> 그럼 viewMdoel은 어떻게 처리하나요? viewModel 패키지를 만들어야 할까요

음 그럼, 패키지 명을 screen이 아니라 feature로 나누면 될거같아요.

2024-07-25 09:05 UTC, 8954sood commented
> 그리고 패키지에 대문자가 안된다면 school_code 이런식으로 해야하나요?

schoolcode 그대로 붙여쓰시면 될것 같아요

2024-07-26 04:48 UTC, 8954sood approved these changes
수고하셨습니다.

2024-07-26 10:35 UTC, merged