Feature/Create Workspace Detail And Member View
apeun-gidaechi/seugi-android pull request #196
Opened 2024-08-13 11:07 UTC by wnsgur1

## 개요 (필수)

- 워크페이스 디테일 뷰와 기능
- 워크페이스 멤버 뷰
- 약간의 컴포넌트 변경

## 이슈 번호

- close #I195

2024-08-13 11:07 UTC, wnsgur1 commented
workspace detail만 만들고 올렸어야 했는데 member screen까지 만들었네요 하하;;

2024-08-14 05:38 UTC, 8954sood requested changes
반영해주세요! :)

2024-08-14 05:38 UTC, 8954sood commented on data/workspace/src/main/java/com/seugi/data/workspace/model/WorkspaceModel.kt
> +    val student: ImmutableList<Long> = listOf<Long>(0).toImmutableList(),
persistentListOf 를 사용하면 toImmutableList를 사용하지 않아도 됩니다.

2024-08-14 05:38 UTC, 8954sood commented on designsystem/src/main/java/com/seugi/designsystem/component/Dropdown.kt
> +    item: List<String>,
List보다 ImmutableList가 좋을 것 같습니다.

2024-08-14 05:38 UTC, 8954sood commented on feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
> +    val nowWorkspace: Pair<String, String> = Pair("", ""),
WorkspaceModel이 아닌, Pair를 사용하는 이유가 있나요?

2024-08-14 05:38 UTC, 8954sood commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailViewModel.kt
> +                    }
이렇게 사이드 이펙트에서 에러를 처리하는 것이 아닌, throwable을 printStackTrace를 통해 에러를 로그에 출력하고, sideEffect를 통해 에러의 내용을 전달해야합니다.

2024-08-14 05:38 UTC, 8954sood commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
> +}
```suggestion
sealed interface WorkspaceDetailSideEffect {
    data class Error(val throwable: Throwable) : WorkspaceDetailSideEffect
}
```
으로 하는게 적절한 것 같습니다.

2024-08-14 05:38 UTC, 8954sood commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
> +    val waitWorkspace: ImmutableList<WaitWorkspaceModel?> = listOf(WaitWorkspaceModel()).toImmutableList(),
```suggestion
    val myWorkspace: ImmutableList<WorkspaceModel?> = persistentListOf(WorkspaceModel())
    val waitWorkspace: ImmutableList<WaitWorkspaceModel?> = persistentListOf(WaitWorkspaceModel())
```

2024-08-14 05:38 UTC, 8954sood commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
> +    val waitWorkspace: ImmutableList<WaitWorkspaceModel?> = listOf(WaitWorkspaceModel()).toImmutableList(),
그리고 더미 모델을 state에 넣는 이유가 있나요?

2024-08-14 05:38 UTC, 8954sood commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
> +)
해당 클래스가 아닌, data.core에 있는 ProfileModel 또는 UserModel을 사용해야합니다.

2024-08-14 05:38 UTC, 8954sood commented on network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
>          const val GET_MY_WORKSPACES = "$WORKSPACE/"
url에서 endpoint의 끝은 슬래쉬가 없도록 해주세요.

2024-08-14 05:40 UTC, wnsgur1 commented on data/workspace/src/main/java/com/seugi/data/workspace/model/WorkspaceModel.kt
> +    val student: ImmutableList<Long> = listOf<Long>(0).toImmutableList(),
오 좋은 정보 감사합니다

2024-08-14 05:44 UTC, wnsgur1 commented on designsystem/src/main/java/com/seugi/designsystem/component/Dropdown.kt
> +    item: List<String>,
하는 김에 위에 dropDown도 ImmutableList로 변경했습니다.

2024-08-14 05:45 UTC, wnsgur1 commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailViewModel.kt
> +                    }
그럼 이제 sideEffect는 성공했을때만 사용할까요?

2024-08-14 05:52 UTC, wnsgur1 commented on feature-main/home/src/main/java/com/seugi/home/model/HomeUiState.kt
> +    val nowWorkspace: Pair<String, String> = Pair("", ""),
워크페이스 모델을 초기화 했놨는지 몰라서 일일이 다 쳤야 한다고 생각해서 사용했는데 워크페이스 모델을 초기화 해놨군요 변경하도록 하겠습니다.

2024-08-14 05:56 UTC, wnsgur1 commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
> +    val waitWorkspace: ImmutableList<WaitWorkspaceModel?> = listOf(WaitWorkspaceModel()).toImmutableList(),
이게 ImmutableList를 초기화 하는 방법을 몰라서 짱구를 돌린결과입니다.

2024-08-14 05:57 UTC, wnsgur1 commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
> +)
더미 데이터라서 이렇게 해놨는데 실제 데이터 넣을때 변경하겠습니다.

2024-08-14 05:59 UTC, wnsgur1 commented on network/core/src/main/java/com/seugi/network/core/SeugiUrl.kt
>          const val GET_MY_WORKSPACES = "$WORKSPACE/"
제거 하겠습니다.

2024-08-14 05:59 UTC, wnsgur1 commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
> +}
변경했습니다.

2024-08-14 06:00 UTC, wnsgur1 commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/WorkspaceDetailViewModel.kt
> +                    }
변경했습니다.

2024-08-14 06:07 UTC, 8954sood approved these changes
수고하셨습니다.

2024-08-14 07:56 UTC, merged