Feature/Create Workspace Member
apeun-gidaechi/seugi-android pull request #203
Opened 2024-08-19 07:49 UTC by wnsgur1

## 개요 (필수)

- 워크페이스 멤버 조회

## 필요 조언
> workspace data 를 참조하는데 왜 core의 값을 참조 못하는 건가요

## 이슈 번호

- close #198

2024-08-19 12:40 UTC, 8954sood requested changes
반영해주세요!

2024-08-19 12:40 UTC, 8954sood commented on feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
> +                                    Log.d("TAG", "홈 워크페이스${state.nowWorkspace.first}, ${state.nowWorkspace.second}: ")
테스트가 끝났다면 지워주세요.

2024-08-19 12:40 UTC, 8954sood commented on feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
> +                Log.d("TAG", "${workspaces[0]} ")
이하동문입니다.

2024-08-19 12:40 UTC, 8954sood commented on feature-main/workspace-detail/build.gradle.kts
> +    implementation(projects.data.core)
data.workspace가 data.core를
api로 참조하면 됩니다.
[참고 자료](https://mangkyu.tistory.com/296)

2024-08-19 12:40 UTC, 8954sood commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
> +    val waitWorkspace: ImmutableList<WaitWorkspaceModel?> = persistentListOf(),
List type에 null을 넣는 이유가 있나요?

2024-08-19 12:40 UTC, 8954sood commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
> +    Log.d("TAG", "${state.member}: ")
리컴포지션이 일어날때마다 로그가 찍히므로 지워주세요.

2024-08-19 22:33 UTC, wnsgur1 commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
> +    val waitWorkspace: ImmutableList<WaitWorkspaceModel?> = persistentListOf(),
내가 참여한 워크페이스는 로컬에 없을 수 있기에 null을 넣었고 대기 중인 워크페이스는 대기 중인 워크페이스가 없을 수 있기때문에 null을 넣었습니다

2024-08-19 22:33 UTC, wnsgur1 commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacemember/WorkspaceMemberScreen.kt
> +    Log.d("TAG", "${state.member}: ")
제거 하였습니다.

2024-08-19 22:33 UTC, wnsgur1 commented on feature-main/home/src/main/java/com/seugi/home/HomeViewModel.kt
> +                Log.d("TAG", "${workspaces[0]} ")
제거 하였습니다.

2024-08-19 22:33 UTC, wnsgur1 commented on feature-main/home/src/main/java/com/seugi/home/HomeScreen.kt
> +                                    Log.d("TAG", "홈 워크페이스${state.nowWorkspace.first}, ${state.nowWorkspace.second}: ")
제거 하였습니다.

2024-08-19 22:34 UTC, wnsgur1 commented on feature-main/workspace-detail/build.gradle.kts
> +    implementation(projects.data.core)
오 감사합니다.

2024-08-19 23:33 UTC, 8954sood commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
> +    val waitWorkspace: ImmutableList<WaitWorkspaceModel?> = persistentListOf(),
size가 0인거랑, 아이템이 null 인거랑 똑같지 않나요?
그래서 굳이 null을 허용해줄 필요가 없을 것 같습니다.

2024-08-19 23:33 UTC, 8954sood approved these changes
수고하셨습니다

2024-08-20 01:16 UTC, wnsgur1 commented on feature-main/workspace-detail/src/main/java/com/seugi/workspacedetail/feature/workspacedetail/model/WorkspaceDetailUiState.kt
> +    val waitWorkspace: ImmutableList<WaitWorkspaceModel?> = persistentListOf(),
동의합니다.

2024-08-20 01:23 UTC, merged