Feature/Move Profile Data
apeun-gidaechi/seugi-android pull request #240
Opened 2024-09-05 10:51 UTC by wnsgur1

## 개요 (필수)

- 메인에서 가져온 프로필을 프로필 화면에 보내기

## 이슈 번호

- close #239

2024-09-05 14:26 UTC, 8954sood requested changes

2024-09-05 14:26 UTC, 8954sood commented on feature-main/main/src/main/java/com/seugi/main/model/MainUiState.kt
> +    ),
이렇게 된다면, workspaceId가 따로 존재하지 않아도 될것 같아요.
그리고 profile은 자신의 것을 state에 올리기에 굳이 myProfile보다는 profile로 변수명을 수정해도 괜찮을 것 같습니다.

2024-09-06 02:24 UTC, wnsgur1 commented on feature-main/main/src/main/java/com/seugi/main/model/MainUiState.kt
> +    ),
워크페이스를 변경했을때 myProfile.workspaceId에 값을 넣는 방법이 궁금합니다.
```
    fun loadLocalWorkspaceId() {
        viewModelScope.launch {
            _state.update {
                it.copy(
                    workspaceId = workspaceRepository.getWorkspaceId(),
                )
            }
        }
    }
```

2024-09-06 02:39 UTC, 8954sood commented on feature-main/main/src/main/java/com/seugi/main/model/MainUiState.kt
> +    ),
myProfile도 state와 마찬가지로 data class이기에 copy 함수를 지원합니다.
```kotlin
fun loadLocalWorkspaceId() {
        viewModelScope.launch {
            _state.update {
                it.copy(
                    myProfile = it.myProfile.copy(
                        workspaceId = workspaceRepository.getWorkspaceId(),
                    )
                )
            }
        }
    }
```

이런식으로 진행하면 될것 같아요.

2024-09-06 07:49 UTC, 8954sood approved these changes

2024-09-06 10:49 UTC, merged