Feature/Failed Chat Queue Retry
apeun-gidaechi/seugi-android pull request #272
Opened 2024-09-29 12:20 UTC by 8954sood

## 개요 (필수)

- 채팅이 실패할 경우, 재전송 하는 로직을 작성하였습니다.
- 이미지, 파일 전송 로직을 작성하였습니다.
- 기존 채팅 로직이 현재 서버로직에 맞지 않다 판단하여 로직을 새로 작성하였습니다.
- 이미지, 파일 다운로드를 구현하였습니다.
- 이미지 프리뷰를 통해 확대, 축소 및 다운로드, 보내기가 가능합니다.
- Chat Item의 height가 잘못 지정되는 버그를 해결하였습니다.

## 이슈 번호

- close #236
- close #268 
- close #269 
- close #271

2024-09-29 23:53 UTC, wnsgur1 requested changes
수고하셨습니다.

2024-09-29 23:53 UTC, wnsgur1 commented on data/file/src/main/java/com/seugi/data/file/repository/FileRepositoryImpl.kt
>          val response = fileDataSource.fileUpload(file = file, type = type.name).data
safeResponse를 사용하지 않은 이유가 있을까요?

2024-09-29 23:53 UTC, wnsgur1 commented on data/message/src/main/java/com/seugi/data/message/mapper/MessageLoadMapper.kt
> +    firstMessageId = firstMessageId,
userId는 Long타입이지 않나요?

2024-09-29 23:53 UTC, wnsgur1 commented on data/message/src/main/java/com/seugi/data/message/mapper/MessageRoomEventMapper.kt
> +internal fun MessageRoomEventResponse.MessageParent.Message.toModel(userId: Int): MessageRoomEvent.MessageParent = when (type) {
userId는 Long타입 아닌가요?

2024-09-29 23:53 UTC, wnsgur1 commented on network/sign-in/src/main/java/com/seugi/network/request/EmailSignInRequest.kt
> +    val token: String = "qwe",
초기화 값이 맞는 건가요?

2024-09-29 23:57 UTC, 8954sood commented on data/message/src/main/java/com/seugi/data/message/mapper/MessageLoadMapper.kt
> +    firstMessageId = firstMessageId,
data core에 존재하는 UserModel의 id가 Int 타입이여서 통일하였습니다.

2024-09-29 23:57 UTC, 8954sood commented on data/message/src/main/java/com/seugi/data/message/mapper/MessageRoomEventMapper.kt
> +internal fun MessageRoomEventResponse.MessageParent.Message.toModel(userId: Int): MessageRoomEvent.MessageParent = when (type) {
data core에 존재하는 UserModel의 id가 Int 타입이여서 통일하였습니다.

2024-09-29 23:58 UTC, 8954sood commented on data/file/src/main/java/com/seugi/data/file/repository/FileRepositoryImpl.kt
>          val response = fileDataSource.fileUpload(file = file, type = type.name).data
수정하겠습니다.

2024-09-30 00:00 UTC, 8954sood commented on network/sign-in/src/main/java/com/seugi/network/request/EmailSignInRequest.kt
> +    val token: String = "qwe",
현재 token을 보내는 로직이 없지만, 서버에서는 없다면 로그인 실패를 반환하여 저렇게 처리하였습니다.

2024-09-30 00:06 UTC, wnsgur1 approved these changes

2024-09-30 00:09 UTC, merged