Feat/Design System Dropdown
apeun-gidaechi/seugi-android pull request #35
Opened 2024-03-31 12:54 UTC by wnsgur1

2024-04-01 00:24 UTC, 8954sood requested changes
수고하셨습니다 😄

2024-04-01 00:24 UTC, 8954sood commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Dropdown.kt
> +fun SeugiDropDown(item: List<String>, title: String, type: DropDownType) {
sealed class를 사용하여 활성화, 비활성화를 구별해야할 이유가 있을까요?

2024-04-01 00:24 UTC, 8954sood commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Dropdown.kt
> +        ) {
이렇게 따로 modifier를 빼는 것 보다
Modifier.clickalbe(
    enable = type != DropDownType.Disabled,
    onClick = {
        isExpanded = !isExpanded
    }
)
로 하는게 더욱 좋아보입니다.

2024-04-01 00:24 UTC, 8954sood commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Dropdown.kt
> +    return calculatedHeight
이렇게 따로 구하는게 아니라, Modifier.heightIn(max = 240.dp)를 활용하면 좋을 것 같습니다.

2024-04-01 00:24 UTC, 8954sood commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Dropdown.kt
> +    val dummyList = listOf("1", "2", "1", "2", "1", "2", "1", "2", "1", "2", "1", "2")
Preview를 Private으로 숨겨주세요!

2024-04-01 05:19 UTC, wnsgur1 commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Dropdown.kt
> +fun SeugiDropDown(item: List<String>, title: String, type: DropDownType) {
저도 활성화, 비활성화 조건을 몰라서 SeugiDropDown안에서 처리하는게 아니라 Type을 지정하는 방식으로 하였습니다

2024-04-01 05:22 UTC, wnsgur1 commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Dropdown.kt
> +    return calculatedHeight
이런 방법이 있었군요.
감사합니다.

2024-04-01 07:48 UTC, wnsgur1 commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Dropdown.kt
> +        ) {
수정하였습니다

2024-04-01 07:48 UTC, wnsgur1 commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Dropdown.kt
> +    val dummyList = listOf("1", "2", "1", "2", "1", "2", "1", "2", "1", "2", "1", "2")
숨겼습니다

2024-04-02 10:27 UTC, 8954sood requested changes
review를 확인해주세요!

2024-04-02 10:27 UTC, 8954sood commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Dropdown.kt
> +fun SeugiDropDown(item: List<String>, title: String, type: DropDownType) {
Dropdown Item을 클릭했을때 이벤트를 상단으로 넘겨주세요.

2024-04-02 10:27 UTC, 8954sood commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Dropdown.kt
> +    }
선택된 아이템을 하위 컴포넌트에서 들고있지 않고 상위 컴포넌트에서 제어하도록 해주세요.

2024-04-02 10:27 UTC, 8954sood commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/OAuthButton.kt
> +fun OAuthButton(image: Int, text: String, onClick: () -> Unit, modifier: Modifier = Modifier) {
image를 @DrawableRes 를 사용해서 res/drawable 에 있는 리소스만 사용가능하다는 것을 강조해주세요.

2024-04-03 02:09 UTC, wnsgur1 commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Dropdown.kt
> +fun SeugiDropDown(item: List<String>, title: String, type: DropDownType) {
기능 추가하였습니다.

2024-04-03 02:09 UTC, wnsgur1 commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/Dropdown.kt
> +    }
수정하였습니다.

2024-04-03 02:09 UTC, wnsgur1 commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/OAuthButton.kt
> +fun OAuthButton(image: Int, text: String, onClick: () -> Unit, modifier: Modifier = Modifier) {
추가하였습니다

2024-04-04 07:10 UTC, 8954sood approved these changes
수고하셨습니다 😄

2024-04-04 07:10 UTC, merged