Feature/Design System Topbar
apeun-gidaechi/seugi-android pull request #51
Opened 2024-04-02 11:15 UTC by wnsgur1

2024-04-02 11:19 UTC, 8954sood requested changes
리뷰를 반영해주세요!

2024-04-02 11:19 UTC, 8954sood commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/TopBar.kt
> +                }
그림자를 활성화,비활성화 하는 기능을 추가해주세요.

2024-04-02 11:36 UTC, 8954sood requested changes

2024-04-02 11:36 UTC, 8954sood commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/TopBar.kt
> +        }
Theme를 제외해주세요!

2024-04-03 02:16 UTC, wnsgur1 commented on designsystem/src/main/java/com/apeun/gidaechi/designsystem/component/TopBar.kt
> +        }
다른 곳에도 Theme에 들어가있으면 제외 시킬까요?
Topbar에서는 제외하였습니다.

2024-04-04 07:08 UTC, 8954sood approved these changes
수고하셨습니다.

2024-04-04 07:09 UTC, merged