Feature/Create Join Screen
apeun-gidaechi/seugi-android pull request #90
Opened 2024-04-27 07:01 UTC by wnsgur1

2024-04-27 08:13 UTC, 8954sood requested changes

2024-04-27 08:20 UTC, wnsgur1 commented on feature-onboarding/join/src/main/java/com/apeun/gidaechi/SelectingJob.kt
> +                                contentScale = ContentScale.Fit,
있으나 없으나 차이는 없지만 제가 깜박하고 삭제하지 못한것 입니다.

2024-04-27 08:20 UTC, wnsgur1 commented on feature-onboarding/join/src/main/java/com/apeun/gidaechi/SelectingJob.kt
> +                                ),
추가하였습니다.

2024-04-27 08:25 UTC, 8954sood requested changes

2024-04-27 08:25 UTC, 8954sood commented on feature-onboarding/join/src/main/java/com/apeun/gidaechi/EmailVerification.kt
> +    val formattedTime = "%d분 %02d초 남음".format(minutes, seconds)
포멧으로 하시는 이유가 있으신가요?

2024-04-27 08:39 UTC, wnsgur1 commented on feature-onboarding/join/src/main/java/com/apeun/gidaechi/EmailVerification.kt
> +    val formattedTime = "%d분 %02d초 남음".format(minutes, seconds)
더 좋은 방식이 있다면 알려주세요

2024-05-06 23:39 UTC, 8954sood requested changes

2024-05-06 23:39 UTC, 8954sood commented on feature-onboarding/join/src/main/java/com/apeun/gidaechi/SelectingJob.kt
> +                                    .offset(y = (4).dp),
굳이 괄호로 감싸야 할까요?

2024-05-06 23:39 UTC, 8954sood commented on feature-onboarding/join/src/main/java/com/apeun/gidaechi/SelectingJob.kt
> +                                    .offset(y = (4).dp),
위와 동일합니다.

2024-05-06 23:47 UTC, wnsgur1 commented on feature-onboarding/join/src/main/java/com/apeun/gidaechi/SelectingJob.kt
> +                                    .offset(y = (4).dp),
y = (-2).dp
이렇게 사용하는 부분이 있어 괄호가 들어간거 같습니다.

2024-05-07 08:46 UTC, 8954sood approved these changes

2024-05-07 08:47 UTC, merged