Feature/Link Onboarding Views
apeun-gidaechi/seugi-android pull request #93
Opened 2024-05-02 08:29 UTC by wnsgur1

2024-05-06 23:49 UTC, 8954sood requested changes
각각의 뷰를 모두 모듈로 분리해주세요.

2024-05-06 23:49 UTC, 8954sood commented on app/src/main/java/com/apeun/gidaechi/seugi/OnboardingActivity.kt
> +}
One Activity 형식으로 사용할 것 같은데, 수정해주세요!

2024-05-06 23:49 UTC, 8954sood commented on feature-onboarding/join/src/main/java/com/apeun/gidaechi/EmailSignUp.kt
> +internal fun EmailSignUpScreen(navHostController: NavHostController) {
직접적으로 navController를 받지 않고, 람다식으로 상위에서 처리하게 변경해주세요.

2024-05-06 23:49 UTC, 8954sood commented on feature-onboarding/onabording/build.gradle.kts
> +    implementation(project(":designsystem"))
중복되는 참조를 제거해주세요.

2024-05-06 23:49 UTC, 8954sood commented on feature-onboarding/start/build.gradle.kts
> +    implementation(project(":designsystem"))
마찬가지입니다.

2024-05-06 23:49 UTC, 8954sood commented on app/build.gradle.kts
> +    implementation(projects.featureOnboarding.onabording)
쓰지 않는 모듈의 참조와, 폴더 자체를 제거해주세요.

2024-05-07 04:55 UTC, wnsgur1 commented on feature-onboarding/onabording/build.gradle.kts
> +    implementation(project(":designsystem"))
제거했습니다.

2024-05-07 10:36 UTC, merged