Feature/Email SignIn
apeun-gidaechi/seugi-android pull request #98
Opened 2024-05-21 09:17 UTC by wnsgur1

2024-06-04 08:48 UTC, 8954sood requested changes
직접적인 data module은 존재하지 않고, 자식들을 감싸는 패키지의 형태로서만 존재해야합니다.
수정부탁드릴게요.

2024-06-04 08:48 UTC, 8954sood commented on data/email-sign-in/src/main/java/com/apeun/gidaechi/data/di/EmailSignInRepositoryModule.kt
> +}
싱글톤을 사용해주세요.

2024-06-04 08:48 UTC, 8954sood commented on feature-main/main/src/main/java/com/apeun/gidaechi/main/MainScreen.kt
> +fun MainScreen(navHostController: NavHostController = rememberNavController()) {
internal을 삭제하신 이유가 있으실까요?

2024-06-04 08:48 UTC, 8954sood commented on feature-onboarding/onabording/src/main/java/com/apeun/gidaechi/OnboardingScreen.kt
> +fun OnboardingScreen(navHostController: NavHostController = rememberNavController(), onboardingToMain: () -> Unit) {
마찬가지 입니다.

2024-06-04 08:48 UTC, 8954sood commented on network/sign-in/src/main/java/com/apeun/gidaechi/network/datasource/EmailSignInDatasourceImpl.kt
> +    override suspend fun emailSignIn(body: EmailSignInRequest): BaseResponse<EmailSignInResponse> = httpClient.post("${SeugiUrl.Auth.EMAIL_SIGN_IN}") {
따옴표로 감싸지 않아도 될 것 같습니다.

2024-06-12 04:47 UTC, wnsgur1 commented on data/email-sign-in/src/main/java/com/apeun/gidaechi/data/di/EmailSignInRepositoryModule.kt
> +}
하하 깜박했네요

2024-06-12 04:49 UTC, wnsgur1 commented on feature-main/main/src/main/java/com/apeun/gidaechi/main/MainScreen.kt
> +fun MainScreen(navHostController: NavHostController = rememberNavController()) {
이게 제가 네비게이션 문제를 해결하다 삭제가 된거 같습니다.
방법을 찾았고 접근제한자를 다시 추가하였습니다.

2024-06-12 04:49 UTC, wnsgur1 commented on network/sign-in/src/main/java/com/apeun/gidaechi/network/datasource/EmailSignInDatasourceImpl.kt
> +    override suspend fun emailSignIn(body: EmailSignInRequest): BaseResponse<EmailSignInResponse> = httpClient.post("${SeugiUrl.Auth.EMAIL_SIGN_IN}") {
옳은 말씀이십니다.

2024-06-12 11:44 UTC, 8954sood approved these changes
수고하셨습니다!

2024-06-12 11:45 UTC, merged